### ISSUE TITLE
errors when running "evaluate_methods.py"

### ISSUE THREAD

**Issue by genereum** [williamleif/socialsent#1]
I get the following warning and exception while running $ python evaluate_methods.py twitter

WARNING:
/usr/lib64/python2.7/site-packages/sklearn/metrics/classification.py:1074: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

EXCEPTION:
Traceback (most recent call last):
  File "evaluate_methods.py", line 625, in <module>
    evaluate_twitter_methods()
  File "evaluate_methods.py", line 461, in evaluate_twitter_methods
    **DEFAULT_ARGUMENTS)
  File "evaluate_methods.py", line 494, in run_method
    return method(embeddings, positive_seeds, negative_seeds, **kwargs)
  File "/home/michel/bin/socialsent/polarity_induction_methods.py", line 224, in bootstrap
    polarities_list = pool.map(map_func, range(num_boots))
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 567, in get
Learning embedding transformation
    raise self._value
Exception: Error when checking model target: expected y to have shape (None, 400) but got array with shape (36, 1)

Thank you for any feedback.

**Comment by williamleif** [comment]
That warning is just an artifact of getting the F1-score when predicting the majority label baseline and is nothing to worry about. I am working on replicating your other error now.

**Comment by williamleif** [comment]
Okay, it looks like an issue coming from keras and/or theano (so it should only happen when evaluating the "densify" method). Do you know what versions of these packages you have?

**Comment by genereum** [comment]
I've just installed all packages needed today, so it must be the latest versions.

**Comment by williamleif** [comment]
Confirmed. Keras recently made some changes that are not compatible. You have two options: (1) install Keras 0.3.3 (should be possible via pip or manually from github)  or (2) remove/comment out all code that uses the "densify" method. 

I will look into making the code compatible with the updated keras, but I unfortunately won't get to this in the immediate future. If you want to fix this and make a pull request that is welcome as well :)

**Comment by genereum** [comment]
Hi Will,

Back to you with some memory issues. My experience so far is that SocialSent runs into memory problem when you reach a threshold of more or less 7000 words to score. So I ran it on a distributed architecture (shartcnet) with 38000 words to score and ask for 16G memory, yet it very soon runs out of memory again:

...
Using Theano backend.
/opt/sharcnet/python/2.7.8/intel/lib/python2.7/site-packages/scipy/lib/_util.py:35: DeprecationWarning: Module scipy.linalg.blas.fblas is deprecated, use scipy.linalg.blas instead
  DeprecationWarning)
Evaluating SentProp with 100 dimensional GloVe embeddings
Evaluating binary and continuous classification performance
LEXICON
SEEDS
EMBEDDINGS
EVAL_WORDS
Traceback (most recent call last):
  File "concreteness.py", line 95, in <module>
    sym=True, arccos=True)
  File "/home/genereum/socialsent-master/polarity_induction_methods.py", line 99, in random_walk
    M = transition_matrix(embeddings, **kwargs)
  File "/home/genereum/socialsent-master/graph_construction.py", line 62, in transition_matrix
    return Dinv.dot(L).dot(Dinv)
MemoryError
--- SharcNET Job Epilogue ---
              job id: 12138822
         exit status: 1
            cpu time: 313s / 12.0h (0 %)
        elapsed time: 479s / 12.0h (1 %)
      virtual memory: 11.9G / 16.0G (74 %)

Job returned with status 1.
WARNING: Job only used 1 % of its requested walltime.
WARNING: Job only used 0 % of its requested cpu time.
WARNING: Job only used 65 % of allocated cpu time.
WARNING: Job only used 74% of its requested memory.
...

A solution would be to run it 7000 words at time. But maybe you know a way to increase the memory use by the program?

Thanks,
Michel

**Comment by williamleif** [comment]
Hi Michel,

I believe this is an issue with numpy. I've ran into these memory issues on a machine with 1Tb of RAM even when I was only using <100Gb. Basically, it is the Dinv.dot(L).dot(Dinv) that takes a lot of memory and you will need to distribute this matrix operation if you want things to be really efficient. Since the code only using the nearest neighbors from this computation, it could also be made more memory efficient by analyzing each row at a time and discarding useless info on the fly (if that makes sense), though this will have a big runtime penalty.

But I think numpy fails at these large matrix operations in general, so doing this right might be a bit tricky.  I was planning on addressing this at some point, but it definitely won't be for another couple weeks at least (I am traveling). 

If you want to try to optimize Dinv.dot(L).dot(Dinv) and submit a pull request that would be great though!

**Comment by williamleif** [comment]
Just to clarify: Numpy will fail to compute Dinv.dot(L).dot(Dinv) even when there is enough RAM due to internal memory size limitations. But the memory requirements are still huge in general and it will be necessary to make an optimized version of the Dinv.dot(L).dot(Dinv) computation.

**Comment by genereum** [comment]
I see. Let me ask you something else, if I may.

A colleague of mine wonders if we could improve performance by incorporating known predictors of concreteness, like word length/morphological complexity, word frequency, or some of the other semantic-space derived ones, like semantic diversity (log mean cosine distance between all a word's contexts). is there room in one of the polarity induction methods to include this? Or perhaps in the embeddings?

Thanks so much!
Michel
________________________________________

**Comment by williamleif** [comment]
I think the most straightforward way to incorporate such features would be
to simply append them to the existing embeddings (and re-normalize the
embeddings after).

If you use the simple linear induction method then I think that this could
improve performance substantially (this method is also not very
memory-intensive). I am not as confident about how this would work the
other methods, however. My intuition is that this could work with the
SentProp-like methods (e.g., label_propagate_probabilistic), but that it
would not work as well with  densify, (since that method tries to find only
one embedding dimension that is most predictive of the label).

Let me know how it turns out!

Cheers,
Will

**Comment by genereum** [comment]
William,

Ok, to " append them to the existing embeddings (and re-normalize the embeddings after).", is there a particular python script in your package to start with or should I look toward something like word2vec ?

Cheers,
Michel
________________________________________
