### ISSUE TITLE
I  am confused, how this project induce sentiment lexicon without help of existed domain-specifc lexicon

### ISSUE THREAD

**Issue by zesoon** [williamleif/socialsent#10]
`acc, auc, avg_prec = binary_metrics(polarities, lexicon, eval_words)`
It seems get the best result (acc, auc, avg_prec) with the help of the baseline domain-specific lexicon(lexicon). 
I am confused how this project induce domain-specific lexicon without the help of existed domain-specific lexicon. How the sentiment words are assigned, `polarities["good"]` is the positive score of word "good" ? and What is the negative score of word "good" .

Thank you for any feedback.

**Comment by williamleif** [comment]
Hi zesoon! Sorry if the code/paper was not totally clear! The code/algorithm requires a "seed" lexicon in order to induce a larger lexicon. 

Using a seed lexicon the algorithm assigns both positive and negative scores to all words in a larger set. The word "good", for example, will have a much higher positive score than negative score. 

I recommend checking out the paper that is linked in the README for more details.

**Comment by zesoon** [comment]
Hi, wil

Thank you for your feedback. In the paper, it defined the positive-polarity score as: Positive_labelscore/(Positive_labelscore+Negative_labelscore), what is the final sentiment score of the word? it is `2*Positive_labelscore/(Positive_labelscore+Negative_labelscore)-1`? Since, when i run the example.py in the project it seems that more words positive-polarity are larger than 0.5 (Positive_labelscore>Negative_labelscore), for example, the example.py output 536 words whose positive-polarity scores are smaller than 0.5, while 2906 words' positive-polarity scores are larger than 0.5.

thanks again
