### ISSUE TITLE
How to use SVDEmbedding?

### ISSUE THREAD

**Issue by lcanalesz** [williamleif/socialsent#8]
Hi William,

I've some doubts about how to use SVDEmbedding. If I'm not mistaken, this method significantly outperformed wor2vec and GloVe on preliminary experiments with the domain-specific data, as I read in the paper. So, I'd like to use it to build my words embeddings.

When I modify the example.py and put:
`embeddings = create_representation("SVD", "data/example_embeddings/glove.6B.100d.txt")`
I receive this message: 
`IOError: [Errno 2] No such file or directory: 'socialsent/data/word_embeddings/glove.6B.100d.txt-u.npy'`

Checking the method, I see that I need three files:
`ut = np.load(path + '-u.npy')`
`s = np.load(path + '-s.npy')`
`vocabfile = path + '-vocab.pkl'`

What contains each file? Sorry, if the question is simple or obvious, but I'm new in word embedding.

Thank you so much!
Lea

**Comment by williamleif** [comment]
Hi Lea,

If you want to use SVD embeddings it is actually a bit of work because you will need to create new SVD embeddings yourself for the domain you are interested in.  To use my code, the workflow would be to

1. Use representations/cooccurgen.py (or something analogous) to process a corpus and construct co-occurrence matrices.
2. Use representations/ppmigen.py to construct PPMI matrices from the co-occurrence matrices.
3. Use representations/makelowdim.py to construct SVD embeddings from the PPMI matrices. 

Are you trying to use the code for a particular domain corpus?

Best,
Will

**Comment by lcanalesz** [comment]
Hi Will,

Thanks for your quick answer :+1: 

Yes, my idea is to use the code for two domains: movies and politics. I will try to build SVD embeddings, as you say. 

Although, I also can build the word embeddings using GloVe or Word2vec and use these pre-trained vectors to build the lexicon in each domain. For that, I would have to use GigaEmbedding, as in example.py. But the GigaEmbedding class needs a lexicon to run, right? I don't understand clearly why I need the lexicon for build the embeddings. Again, sorry if the question is too obvious.

Thanks again! :)
Lea

**Comment by williamleif** [comment]
Hi Lea,

Sorry for the late response this time! It's been a crazy couple weeks. 

Yes, if you want to build lexicons for your own specific domain, the easiest solution would be to learn domain-specific word2vec embeddings for your domain and then you can feed those learned embeddings into socialsent as is done with the GigaEmbedding class. You could use something like gensim (https://radimrehurek.com/gensim/models/word2vec.html) to learn the embeddings, which is very polished production code. 

You will also need a seed lexicon to induce the new lexicons (line 18 in example.py). The only reason I use the full lexicon when constructing the GigaEmbeddings in example.py (line 12) is that I only load embeddings for words that are in the lexicon (just to keep the memory footprint low). This is not essential and you don't really need to worry about this for your use case. The third argument of create_representation is just a set of words that you want to load embeddings for (again, just so that you don't unnecessarily load embeddings for a million words when you are only interested in a smaller set of words).

Hope that helps!! 

I am going to close this issue for now, but please open a new ones if there are more specific things you run into. You could also email me for general advice, but I will warn that I might not be able to respond immediately, especially over the next month when is quite busy with another (not yet publicly released) project.

Best,
Will
